# Generated by Django 4.1 on 2023-07-11 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emotion', '0002_text_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='patient_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
